"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import core.crypto
import core.money


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('bl_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bl_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bl_views_symbol'), ['symbol'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', core.crypto.EncryptedString(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('investment_horizon_years', sa.Integer(), nullable=False),
    sa.Column('monthly_income', core.crypto.EncryptedDecimal(length=255), nullable=False),
    sa.Column('declared_risk_tolerance', sa.Integer(), nullable=False),
    sa.Column('financial_goal', sa.Text(), nullable=True),
    sa.Column('advisor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_advisor_user_id'), ['advisor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_email_hash'), ['email_hash'], unique=True)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('yahoo_symbol', sa.String(length=32), nullable=True),
    sa.Column('tefas_code', sa.String(length=16), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('expense_ratio', sa.Float(), nullable=False),
    sa.Column('liquidity_days', sa.Integer(), nullable=False),
    sa.Column('min_trade_amount', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('sector', sa.String(length=48), nullable=True),
    sa.Column('esg_member', sa.Boolean(), nullable=False),
    sa.Column('esg_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_asset_class'), ['asset_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_symbol'), ['symbol'], unique=True)

    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('purpose', sa.String(length=48), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_created_at'), ['created_at'], unique=False)

    op.create_table('macro_series',
    sa.Column('series', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('series', 'date')
    )
    op.create_table('model_portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('class_weights', sa.JSON(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('expected_volatility', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'version', name='uq_model_portfolio_version')
    )
    with op.batch_alter_table('model_portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_portfolios_level'), ['level'], unique=False)

    op.create_table('price_history',
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('cash', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('holdings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_customer_id'), ['customer_id'], unique=False)

    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=16), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('capacity_score', sa.Float(), nullable=False),
    sa.Column('tolerance_score', sa.Float(), nullable=False),
    sa.Column('knowledge_score', sa.Float(), nullable=False),
    sa.Column('capacity_level', sa.Integer(), nullable=False),
    sa.Column('tolerance_level', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'version', name='uq_risk_profile_version')
    )
    with op.batch_alter_table('risk_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_profiles_customer_id'), ['customer_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # customers ↔ users döngüsel bağımlılığı: FK, iki tablo da oluştuktan sonra eklenir.
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_customers_advisor', 'users', ['advisor_user_id'], ['id'], ondelete='SET NULL'
        )

    op.create_table('advisor_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('market_input', sa.JSON(), nullable=False),
    sa.Column('target_weights', sa.JSON(), nullable=False),
    sa.Column('orders', sa.JSON(), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisor_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_runs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_runs_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('autopilot_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cash_threshold', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('target_symbol', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_flows_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('goal_type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount_real', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('horizon_years', sa.Float(), nullable=False),
    sa.Column('initial_amount', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('monthly_contribution', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('portfolio_share', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('last_simulation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_customer_id'), ['customer_id'], unique=False)

    op.create_table('nudges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nudges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nudges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nudges_customer_id'), ['customer_id'], unique=False)

    op.create_table('rebalance_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('model_level', sa.Integer(), nullable=True),
    sa.Column('target_weights', sa.JSON(), nullable=False),
    sa.Column('before_weights', sa.JSON(), nullable=False),
    sa.Column('after_weights', sa.JSON(), nullable=False),
    sa.Column('orders', sa.JSON(), nullable=False),
    sa.Column('prices', sa.JSON(), nullable=False),
    sa.Column('estimated_cost', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('estimated_tax', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('turnover', sa.Float(), nullable=False),
    sa.Column('risk_before', sa.JSON(), nullable=False),
    sa.Column('risk_after', sa.JSON(), nullable=False),
    sa.Column('optimizer', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('suitability', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('llm_mode', sa.String(length=16), nullable=True),
    sa.Column('graph_thread_id', sa.String(length=80), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approval_idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('rebalance_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rebalance_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rebalance_proposals_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rebalance_proposals_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rebalance_proposals_status'), ['status'], unique=False)

    op.create_table('tax_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('quantity_open', core.money.Quantity(precision=20, scale=8), nullable=False),
    sa.Column('quantity_initial', core.money.Quantity(precision=20, scale=8), nullable=False),
    sa.Column('unit_cost', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_lots_acquired_at'), ['acquired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_symbol'), ['symbol'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', core.money.Quantity(precision=20, scale=8), nullable=False),
    sa.Column('price', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('total_amount', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('fees', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('tax', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_ticker'), ['ticker'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', core.money.Quantity(precision=20, scale=8), nullable=False),
    sa.Column('reference_price', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['rebalance_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('quantity', core.money.Quantity(precision=20, scale=8), nullable=False),
    sa.Column('price', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('fees', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('tax', core.money.Money(precision=20, scale=6), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_advisor', type_='foreignkey')
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))

    op.drop_table('fills')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_orders_portfolio_id'))

    op.drop_table('orders')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_ticker'))
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_executed_at'))

    op.drop_table('transactions')
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_lots_symbol'))
        batch_op.drop_index(batch_op.f('ix_tax_lots_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_tax_lots_acquired_at'))

    op.drop_table('tax_lots')
    with op.batch_alter_table('rebalance_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rebalance_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_rebalance_proposals_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_rebalance_proposals_customer_id'))
        batch_op.drop_index(batch_op.f('ix_rebalance_proposals_created_at'))

    op.drop_table('rebalance_proposals')
    with op.batch_alter_table('nudges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nudges_customer_id'))
        batch_op.drop_index(batch_op.f('ix_nudges_created_at'))

    op.drop_table('nudges')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_customer_id'))

    op.drop_table('goals')
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_flows_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_cash_flows_occurred_at'))

    op.drop_table('cash_flows')
    op.drop_table('autopilot_settings')
    with op.batch_alter_table('advisor_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_runs_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_runs_customer_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_runs_created_at'))

    op.drop_table('advisor_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_customer_id'))

    op.drop_table('users')
    with op.batch_alter_table('risk_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_profiles_customer_id'))

    op.drop_table('risk_profiles')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_customer_id'))

    op.drop_table('portfolios')
    op.drop_table('price_history')
    with op.batch_alter_table('model_portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_portfolios_level'))

    op.drop_table('model_portfolios')
    op.drop_table('macro_series')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_created_at'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_symbol'))
        batch_op.drop_index(batch_op.f('ix_instruments_asset_class'))

    op.drop_table('instruments')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email_hash'))
        batch_op.drop_index(batch_op.f('ix_customers_advisor_user_id'))

    op.drop_table('customers')
    with op.batch_alter_table('bl_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bl_views_symbol'))

    op.drop_table('bl_views')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_customer_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
