"""Transaction (İşlem) ORM model.

Every trade executed on a portfolio — whether placed manually or produced by
the Portfolio Manager's rebalancing — is stored here as an immutable ledger
row. The ``side`` field is one of ``BUY`` / ``SELL``.

Taxonomy of ``reason``:
    * ``rebalance`` — generated by the LangGraph rebalancing workflow.
    * ``manual`` — placed through the (CRUD) API.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from sqlalchemy import Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from core.database import Base

if TYPE_CHECKING:
    from models.portfolio import Portfolio


def _utcnow() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


class Transaction(Base):
    """ORM model of the ``transactions`` table."""

    __tablename__ = "transactions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    portfolio_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("portfolios.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    ticker: Mapped[str] = mapped_column(String(16), index=True, nullable=False)
    side: Mapped[str] = mapped_column(String(8), nullable=False)  # BUY | SELL
    quantity: Mapped[float] = mapped_column(Float, nullable=False)
    price: Mapped[float] = mapped_column(Float, nullable=False)
    # quantity * price, denormalized for fast reporting.
    total_amount: Mapped[float] = mapped_column(Float, nullable=False)
    reason: Mapped[str] = mapped_column(String(32), nullable=False, default="manual")
    executed_at: Mapped[datetime] = mapped_column(index=True, default=_utcnow)

    # --- İlişkiler ------------------------------------------------------------
    portfolio: Mapped["Portfolio"] = relationship(back_populates="transactions")

    def __repr__(self) -> str:  # pragma: no cover - debug aid
        return (
            f"<Transaction id={self.id} portfolio_id={self.portfolio_id} "
            f"{self.side} {self.ticker} x{self.quantity} @ {self.price}>"
        )
